<?php include('header.php'); ?> 
<section class="first-section section refund-policy">
    <div class="container">
        <div class="row">
            <div class="refund-policy-div"> 
                <h2>Privacy Policy</h2>
                <p>Perfection Consulting India ("we", "our" or "us") is committed to protecting your privacy. This Privacy Policy explains how</p>
                <p>Perfection Consulting India collects, uses and discloses your personal information. This Privacy Policy applies to our website,</p>
                <p>Perfection Consulting India and its associated subdomains (collectively, our "Service") together with our application,</p>
                <p>Perfection Consulting India. By accessing or using our Platform to Hire Experts, you indicate that you have read, understood and agree to our collection, storage, use and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.</p> 
                
                
                <h3>Definitions and Key Terms</h3>
                <p>To help explain things as clearly as possible in this Privacy Policy, whenever any of these terms are referred to, they are strictly defined as:</p>
                
                <h3>Cookie: </h3>
                <p>small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information. Company: When this policy mentions "Company", "we", "us" or "our", it refers to Perfection Consulting India , which is responsible for your information under this Privacy Policy.</p>
                
                <h3>Platform: </h3>
                <p>Perfection Consulting India Internet website, web application or public-facing digital application</p>
                
                <h3>Country: </h3>
                <p>where Perfection Consulting India or the owners/founders of Perfection Consulting India is located, in this case it is INDIA</p> 
                
                <h3>Customer:</h3>
                <p>refers to the company, organisation or person that registers to use the Perfection Consulting India Service to manage relationships with its consumers or service users</p>
                
                 
                <h3>Device:</h3>
                <p>any device connected to the Internet, such as a phone, tablet, computer or any other device that can be used to visit Perfection Consulting India and use the services. IP Address: Every device connected to the Internet is assigned a number known as an Internet Protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device connects to the Internet.</p>
                
                <h3>Personnel:</h3>
                <p>refers to those persons who are employed by Perfection Consulting India or are under contract to perform a service on behalf of a party.</p>
                
                <h3>Personal data:</h3>
                <p>any information that directly, indirectly or in connection with other information, including a personal identification number, allows the identification of a natural person.</p>
                
                <h3>Service:</h3>
                <p>refers to the service provided to Hire Experts by Perfection Consulting India as described in the relative terms (if available) and on this platform.</p>
                
                <h3>Third Parties:</h3>
                <p>refers to advertisers, contest sponsors, marketing and promotional partners, and others who provide our content or whose products or services we believe may interest you.</p>
                
                <h3>Website:</h3>
                <p>The Perfection Consulting India site, which can be accessed through this URL: Perfection Consulting India</p>
                
                <h3>You:</h3>
                <p>a person or entity who is registered with Perfection Consulting India to use the Platform.</p> 
                
                <h3>Information collected automatically</h3>
                <p>There is certain information such as your Internet Protocol (IP) address and/or browser and device characteristics, that is collected automatically when you visit our platform. This information can be used to connect your computer to the Internet. Other information collected automatically could be a login, email address, password, computer and connection information, such as browser plug-in types and versions and time zone settings, operating systems and platforms, purchase history (sometimes we add similar information from other users), the entire Uniform Resource Locator (URL) clickstream to, through and from our website which may include date and time; cookie number; parts of the site you viewed or searched for; and the phone number you used to call our Customer Service. We may also use browser data such as cookies, Flash cookies (also known as Flash local shared objects), or similar data on certain parts of our website for fraud prevention and other purposes. During your visits, we may use software tools such as JavaScript to measure and collect session information, including page response times, download errors, length of visits to certain pages, page interaction information (such as displacement, clicks and mouse scrolling) and methods used to navigate away from the page. We may also collect technical information to help us identify your device for fraud prevention and diagnosis purposes.</p>
                <p>Information collected automatically There is certain information such as your Internet Protocol (IP) address and/or browser and device characteristics, that is collected automatically when you visit our platform. This information can be used to connect your computer to the Internet. Other information collected automatically could be a login, email address, password, computer and connection information, such as browser plug-in types and versions and time zone settings, operating systems and platforms, purchase history (sometimes we add similar information from other users), the entire Uniform Resource Locator (URL) clickstream to, through and from our website which may include date and time; cookie number; parts of the site you viewed or searched for; and the phone number you used to call our Customer Service. We may also use browser data such as cookies, Flash cookies (also known as Flash local shared objects), or similar data on certain parts of our website for fraud prevention and other purposes. During your visits, we may use software tools such as JavaScript to measure and collect session information, including page response times, download errors, length of visits to certain pages, page interaction information (such as displacement, clicks and mouse scrolling) and methods used to navigate away from the page. We may also collect technical information to help us identify your device for fraud prevention and diagnosis purposes.</p>
                
                <h3>Business Sale</h3>
                <p>We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of Perfection Consulting India or any of its corporate affiliates (as defined herein), or the Perfection Consulting India portion or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed a petition against us in the event of bankruptcy, reorganisation or similar proceeding, provided that the third party agrees adhere to the terms of this Privacy Policy</p>
                
                <h3>Affiliates</h3>
                <p>We may disclose information (including personal information) about you to our corporate affiliates. For purposes of this Privacy Policy, “Corporate Affiliate” means any person or entity that directly or indirectly controls, is controlled by, or is under common control with Perfection Consulting India , whether by ownership or otherwise. Any information relating to you that we provide to our corporate affiliates will be treated by such corporate affiliates in accordance with the terms of this privacy policy.</p>
                
                <h3>Governing Law</h3>
                <p>This Privacy Policy is governed by the laws of INDIA without regard to its conflict of laws provisions. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy, except for those persons who may have the right to bring claims under the Privacy Shield. The laws of INDIA, excluding its conflicts of laws, will govern this Agreement and your use of the Platform. Your use of the Platform may also be subject to other local, state, national or international laws. By using Perfection Consulting India or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not interact with our website or use our services. Your continued use of the Website, direct interaction with us, or following the posting of changes to this Privacy Policy that do not materially affect the use or disclosure of your personal information will mean that you accept those changes.</p>
                
                <h3>Your consent</h3>
                <p>We have updated our Privacy Policy to give you full transparency about what is set when you visit our site and how it is used. By using our platform, registering an account or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.</p>
                 
                <h3>Links to other Websites</h3>
                <p>This Privacy Policy applies only to the Services. The Services may contain links to other websites that are not operated or controlled by Perfection Consulting India We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those linked to on our platform, is subject to that website's own rules and policies. These third parties may use their own cookies or other methods to collect information about you.</p>
                
                <h3>Cookies</h3>
                <p>Perfection Consulting India uses "cookies" to identify the areas of our website that you have visited. A cookie is a small piece of data that your web browser stores on your computer or mobile device. We use cookies to improve the performance and functionality of our platform, but they are not essential for its use. However, without these cookies, certain features, such as videos, may not be available or you may be asked to enter your login details each time you visit the platform as we would not be able to remember that you had logged in previously. Most web browsers can be configured to disable the use of cookies. However, if you disable cookies, you may not be able to access the functionality of our website correctly or at all.</p>
                
                <h3>Block and disable Cookies and similar technologies</h3>
                <p>Wherever you are, you can also set your browser to block cookies and similar technologies, but this may block our essential cookies and prevent our website from functioning properly, and you may not be able to use all of its features and services in full. You should also be aware that you may also lose saved information (e.g. saved login details, site preferences) if you block cookies in your browser. Different browsers provide different controls. Disabling a cookie or a cookie category does not delete the cookie from your browser, you will need to do this yourself from your browser, you should visit your browser's help menu for more information.</p>
                
                <h3>Children's Privacy</h3>
                <p>We do not target anyone under 13 years of age. We do not collect personally identifiable information from anyone under 13 years of age. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact Us. If we become aware that we have collected personal data from anyone under the age of 13 without verification of parental consent, we take steps to delete that information from our servers.</p>
                
                <h3>Changes to our Privacy Policy</h3>
                <p>We may change our Service and our policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and our policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you the opportunity to review them before they become effective. Then, if you continue to use the Service, you will be subject to the updated Privacy Policy. If you do not wish to accept this or any updated Privacy Policy, you may delete your account.</p>
                
                <h3>Third party services</h3>
                <p>We may display, include or make available third party content (including data, information, applications and other product services) or provide links to third party websites or services ("Third Party Services").</p>
                <p>You acknowledge and agree that Perfection Consulting India shall not be responsible or liable for any Third Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof.</p>
                <p>Perfection Consulting India does not assume and shall not have any obligation or liability to you or any other person or entity for any Third Party Services.</p>
                <p>Third Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to the terms and conditions of such third parties.</p>
            </div>
        </div>
    </div>
</section> 

<?php include('footer.php'); ?> 