<?php include('header.php'); ?> 
<section class="first-section section refund-policy">
    <div class="container">
        <div class="row">
            <div class="refund-policy-div">
                <h2>Terms and Services/MOU</h2>
                <p><b>WELCOME TO Perfection Consulting India!</b><br>Since we will not be meeting face to face, it is important to set out the terms of the agreement clearly in advance. If you have any queries about Perfection Consulting India, please do not hesitate to contact us. In this agreement, we have referred to the Perfection Consulting India services as the "service to procure Specialists and Facilitating communication Platform", to you as the "user", to our agreement as the "agreement",  person who have knowledge of G.E.M as Specialists, Experts, Consultant and Professionals. Sometimes we refer “Information form” as “Application form” also. If you wish to use our “Common Needs” feature, you affirm that you are more than 18 years of age and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties consequent to the creation of the documents, and are aware of the same. Kindly call us for further assistance. </p> 
                
                <h3>Perfection Consulting India  PROVIDES A MEDIUM FOR INTERACTION</h3>
                <p>Perfection Consulting India is an internet portal that facilitates communication between Specialists and potential users for Services Related To G.E.M and Information. Perfection Consulting India acts as a venue for providers and consumers of Services Related To G.E.M and Information to exchange information with the goal of eventually forming a Specialists relationship. In order to provide an optimal forum for Specialists and clients, Perfection Consulting India does not involve itself in the agreements between Specialists and clients or the actual representation of clients. Therefore, we cannot ensure the completion of the agreement or the integrity of either party. The user, and not Perfection Consulting India, is solely responsible for assessing the integrity, honesty, and trustworthiness of all persons with whom the user communicates on this service.</p>
                
                <h3>(a) Disclaimer of Experts-client relationship</h3>
                <p>Perfection Consulting India is not an agent of Specialists. Its only a Platform to Procure Specialists for G.E.M Related Services and facilitates the communication of Specialists and potential clients. Any electronic communication sent to Perfection Consulting India alone will not create a expert-client relationship between the user and Perfection Consulting India, such being expressly denied.</p>
                
                <h3>(b) Perfection Consulting India does not promote any User.</h3>
                <p>Perfection Consulting India seeks to help every needy users find Specialists best suited to his/her needs as per Information form or details they shared. Perfection Consulting India is not intended to be a source of advertising or solicitation and the contents of the website should not be construed as legal advice.</p>
                <h3>(c) Perfection Consulting India does not provide any Services, Guidance, Consultancy and Advice related to Government documents in any sense. </h3>
                <p>Perfection Consulting India is a platform from where you can procure Specialists only for Services related to G.E.M as per Information form.</p>
                
                <h3>(d) Services Perfection Consulting India Provides</h3>
                <p>Perfection Consulting India offers services for procuring specialists related to G.E.M services and provides a communication platform only.</p>
                
                <h3>(e) Phrases Uses in Google Ads and in Perfection Consulting India Website</h3>
                <p>The website Perfection Consulting India uses phrases such as 'Apply G.E.M Registration,' 'G.E.M Registration,' 'Online G.E.M Registration' and Similar to emphasize the Ultimate need of user for they want to procure Specialists. However, it's important to note that these phrases do not imply that Perfection Consulting India provides services, advices, consultation and assistance related to G.E.M or promotes the direct acquisition of government documents and services. Perfection Consulting India offers services for procuring specialists related to G.E.M services and provides a communication platform only</p>
                
                <h3>(f) 'Common Needs'- Resale of Forms Prohibited</h3>
                <p>Perfection Consulting India grants you a limited, personal, non-exclusive, non-transferable license to use our “Common Needs” feature for your own personal use, or if you are an attorney or Specialists, for your client. Except as otherwise provided, you acknowledge and agree that you have no right to modify, edit, copy, reproduce, create derivative works of, reverse engineer, alter, enhance or in any way exploit any of the Forms in any manner, except for modifications in filling out the Forms for your authorized use.  </p>
                
                <h3>(g) Disclaimer of representations by users</h3>
                <p>Perfection Consulting India makes no representation, guarantee, or warranty (express or implied) as to the legal ability, competence, or quality of representation which may be provided by any of the Specialists which are listed through this site or any affiliate thereof.</p>
                
                <h3>(h) Allow us to use your details</h3>
                <p>You allow Perfection Consulting India to user your data for evaluate and Remarketing for advertisement purpose for India.Regsitrationportalindia.org.</p>
                
                <h3>Please note that neither Perfection Consulting India, nor any of its subsidies or employees are Specialists. We are not a firm who provide services and we do not provide any advice. </h3>
                <p>Nothing on our website or material sent to you in our communication is to be construed as legal advice. Our website, blog and other material is only for the purpose of spreading information and awareness and are not substitutes for the advices or services of an Specialists or legal Specialists. Wherever required in order to fulfil your needs, we will facilitate a connection with a suitable expert of ours. Please bear in mind that such Specialists are not our representatives, agents or employees. Our site and services are only one source of information among the many sources that are available to you. You may wish to consider multiple sources in order to make an informed decision. The decision to hire Specialists is an important one. If you agree to avail of the services on our website to hire best suitable Specialists for you as per Information form and details you provided, you are giving us permission to make this selection on your behalf. If you disagree with these terms and conditions, or do not want us to choose a suitable Specialists to fulfil your request, please do not use our services. We constantly strive to keep our content and documents accurate, current and up-to date. However, because of changes in the law and regulations, we cannot and do not guarantee that any or all of the information on the site and other communication is completely current. Please be advised that sometimes, the law, legal requirements, rules and regulations are location specific and may differ from location to location. The general information or other material we provide cannot fit every situation or circumstance. Our sites and services are not intended to create any Specialists-client relationship, and your use of our sites and services does not and will not in any circumstance create any such relationship between you and us.</p>
                
                <h3>USER GUIDELINES</h3>
                <p>The users of Perfection Consulting India are granted a nonexclusive, limited right to access and use the service in accordance with the rules that are described in this contract. In order to keep this system attractive and useful for all users, it is important that users follow the rules of the system. Perfection Consulting India reserves the right to deny further access to its service to any user who violates these rules, is the subject of complaints by other Perfection Consulting India users or for any other reason. Users engaged in any of the following activities on our system will not be tolerated:</p>
                
                <p>1 Foul or otherwise inappropriate language.</p>
                <p>2 Racist, hateful, or otherwise offensive comments.</p>
                <p>3  Promote or provide instructional information about illegal activities, or promoting physical harm or injury against any group or individual.</p>
                <p>4  Defame any person or group which includes people of all ages, races, religions, and nationalities.</p>
                <p>5  Violate the rights of another, including but not limited to the intellectual property rights of another. This includes using the service for acts of copyright, trademark, patent, trade secret, or other intellectual property infringement, including but not limited to offering pirated computer programs or links to such programs, information used to circumvent manufacturer-installed copy-protect devices, including serial or registration numbers for software programs, or any type of cracker utilities (this also includes files which are solely intended for game emulation).</p>
                <p>6 Violate Internet standards.</p>
                <p>7  Use the service for displaying harassing, abusive, threatening, harmful, vulgar, obscene, or tortuous material or invading other's privacy.</p>
                <p>8  Interfere with or disrupting the service or servers or networks connected to the service by posting advertisements or links to competing services, transmitting "junk mail", "spam", "chain letters", or unsolicited mass distribution of e-mail.</p>
                <p>9  Compromise the security of the service Perfection Consulting India provides. Please do not try to gain access to system areas private to Perfection Consulting India, or to other users.</p> 
                
                
                <h2> DISCLAIMER OF INFORMATION OBTAINED ON THE SERVICE AND SOME USER SUPPLIED CONTENT</h2>
                <h3>(a) Disclaimer of information obtained on the Service</h3>
                <p>Perfection Consulting India provides Specialists and potential clients with a forum whereby people who need Expert. Perfection Consulting India is a resource for informational purposes and is intended, but not promised or guaranteed to be correct, complete, and up-to-date. The accuracy, completeness or adequacy of Perfection Consulting India is not warranted or guaranteed. Perfection Consulting India further assumes no liability for the interpretation and/or use of the information contained on this website. The owner of this website does not intend links from this site to other websites to be referrals to, endorsements of, or affiliations with the linked entities. Perfection Consulting India is not responsible for, and makes no representations or warranties about the contents of websites to which links may be provided from this website. Perfection Consulting India will make every effort to ensure that promotional material of a user trying to promote himself on the website is deleted. Apart from this, the opinions and views expressed are those of the individual users of the service and do not reflect those of Perfection Consulting India. Data submitted by other users (lay persons) is not verified or reviewed in any way before it appears on the Perfection Consulting India website. Please use due caution when using this site. Perfection Consulting India makes every effort to verify that Specialists who subscribe to the service are experienced and in good standing with the local bar at the time of registration. However, Perfection Consulting India cannot track, verify, or monitor the standing of Specialists using the Service. Therefore, Perfection Consulting India makes no representation regarding the status, standing or ability of Specialists that is listed on the site. Perfection Consulting India is not responsible for, and in no way endorses any description or indication of specialization or limitation of practice by Specialists. Efforts will be made to avoid false information, but please be aware that no agency or board may have certified such Specialists as a specialists or Specialists in any indicated field.</p>
                 
                <p>Users are encouraged to use caution when reviewing any information submitted by Specialists and other parties. Although Perfection Consulting India requires Specialists to comply with all regulations governing Specialists conduct, it is impossible for Perfection Consulting India to monitor Specialists' integrity. Perfection Consulting India in no way endorses the content or legality of any offers, statements, or promises made by Specialists or any other parties, on or off this site.</p>
                
                <h3>LIMITATIONS ON USE</h3>
                <p>The contents of Perfection Consulting India are for personal use only and not for commercial exploitation. You may not decompile, reverse engineer, disassemble, rent, lease, loan, sell, sublicense, or create derivative works from Perfection Consulting India. Nor may you use any network monitoring or discovery software to determine the site architecture, or extract information about usage or users. You may not use any robot, spider, other automatic device, or manual process to monitor or copy the contents without taking prior written permission from Perfection Consulting India. You may not copy, modify, reproduce, republish, distribute, display, or transmit for commercial, non-profit or public purposes all or any portion of Perfection Consulting India, except to the extent permitted above. You may not use or otherwise export or re-export Perfection Consulting India or any portion available on or through Perfection Consulting India in violation of the export control laws and regulations of India. Any unauthorized use of Perfection Consulting India or its content is prohibited.</p>
                
                <h3>CONFIDENTIALITY</h3>
                <p>Perfection Consulting India makes every effort to maintain the confidentiality of any information submitted by users to our system and our database of Specialists. The user is however warned that the use of the internet or e-mail for confidential or sensitive information is susceptible to risks that inevitably arise on this medium. Additionally, because Perfection Consulting India cannot control the conduct of others, we cannot guarantee that this information will remain confidential. Please use caution in deciding what information to input into the System. Do not make any confessions or admissions. The user should preferably describe their issue or dispute in the general terms only. Specific information should only be revealed after the user has assigned an Specialists</p>
                
                <h3>INDEMNIFICATION</h3>
                <p>The user agrees that Perfection Consulting India is not responsible for any harm that his/her use of this service may cause. The user agrees to indemnify, defend, and hold Perfection Consulting India harmless from and against any and all liability and costs incurred in connection with any loss, liability, claim, demand, damage, and expenses arising from or in connection with the contents or use of the service. The user agrees that this defense and indemnity shall also apply to any breach by the user of the agreement or the foregoing representations, warranties and covenants. The user further agrees that this defense and indemnity shall include without limitation of Specialists fees and costs. The user also agrees that this defense and indemnity shall apply to Perfection Consulting India, its founders, officers and employees. Perfection Consulting India reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by the user and the user shall not in any event settle any matter without the written consent of Perfection Consulting India.</p>
                
                <h3>COMMUNICATIONS AND OTHER DATA</h3>
                <p>Perfection Consulting India is not responsible for any loss of data resulting from accidental or deliberate deletion, network or system outages, backup failure, file corruption, or any other reasons.</p>
                
                <h3>LICENSE OF YOUR CONTENTS TO Perfection Consulting India</h3>
                <p>By uploading content to or submitting any materials for use on Perfection Consulting India, you grant (or warrant that the owner of such rights has expressly granted) Perfection Consulting India a perpetual, royalty-free, irrevocable, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate, create derivative works from and distribute such materials or incorporate such materials into any form, medium, or technology now known or later developed. Perfection Consulting India however gives an assurance that any information of a sensitive nature will not be intentionally disclosed and revealed to any third party.</p>
                
                <h3>Perfection Consulting India PROPRIETARY RIGHTS</h3>
                <p>Except as expressly provided in these terms and conditions, nothing contained herein shall be construed as conferring any license or right, by implication, estoppels or otherwise, under copyright or other intellectual property rights. The user agrees that the content and Web Site are protected by copyright, trademark, service marks, patents or other proprietary rights and laws. The user acknowledges and agrees that the user is permitted to use this material and information only as expressly authorized by Perfection Consulting India, and may not copy, reproduce, transmit, distribute, or create derivative works of such content or information without express authorization. The user acknowledges and agrees that Perfection Consulting India can display images and text throughout the Service. Users cannot extract and publish any information from the system, either electronically or in print, without the permission of Perfection Consulting India and the permission of all other concerned parties. This is not a complete list - other things on the system are also Perfection Consulting India property. Contact Perfection Consulting India before copying anything from the system with plans of reproducing it or distributing it.</p>
                
                <h3>LINKING TO Perfection Consulting India</h3>
                <p>Users are welcome to provide links to the homepage of Perfection Consulting India, provided they do not remove or obscure, by framing or otherwise, any portion of the homepage and that you discontinue providing links to the site if requested by Perfection Consulting India.</p>
                
                <h3>ADVERTISERS</h3>
                <p>Perfection Consulting India may contain advertising and sponsorship. Advertisers and sponsors are responsible for ensuring that material submitted for inclusion on Perfection Consulting India is accurate and complies with applicable laws. Perfection Consulting India will not be responsible for the illegality of or any error or inaccuracy in advertisers or sponsors' materials.</p>
                
                <h3>ERRORS AND CORRECTIONS</h3>
                <p>Perfection Consulting India does not represent or warrant that the service will be error-free, free of viruses or other harmful components, or that defects will be corrected. Perfection Consulting India may make improvements and/or changes to its features, functionality or service at any time.</p>
                
                <h3>THIRD PARTY CONTENT</h3>
                <p>Third-party content may appear on Perfection Consulting India or may be accessible via links from Perfection Consulting India. Perfection Consulting India is not responsible for and assumes no liability for any mistakes, misstatements of law, defamation, slander, libel, omissions, falsehood, obscenity or profanity in the statements, opinions, representations or any other form of information contained in any third party content appearing on Perfection Consulting India. You understand that the information and opinions in the third party content is neither endorsed by nor does it reflect the belief of Perfection Consulting India.</p>
                
                <h3>UNLAWFUL ACTIVITY</h3>
                <p>Perfection Consulting India reserves the right to investigate complaints or reported violations of the Agreement and to take any action Perfection Consulting India deems appropriate including but not limited to reporting any suspected unlawful activity to law enforcement officials, regulators, or other third parties and disclosing any information necessary or appropriate to such persons or entities relating to user profiles, e-mail addresses, usage history, posted materials, IP addresses and traffic information.</p>
                
                
                <h3> REMEDIES FOR VIOLATIONS</h3>
                <p>Perfection Consulting India reserves the right to seek all remedies available at law and in equity for violations of the Agreement, including but not limited to the right to block access from a particular Internet address to Perfection Consulting India and its features.</p>
                
                <h3>SEVERABILITY OF PROVISIONS</h3>
                <p>The Agreement and the Privacy Policy constitute the entire agreement with respect to the use of the service provided by Perfection Consulting India. If any provision of these terms and conditions is unlawful, void or unenforceable then that provision shall be deemed severable from the remaining provisions and shall not affect their validity and enforceability.</p>
                
                <h3>MODIFICATIONS TO TERMS OF USE</h3>
                <p>Perfection Consulting India may change the agreement at any time. The user will be responsible for checking the Terms and Conditions before use. Use of the service after the change will indicate acceptance of the new terms and conditions.</p>
                
                <h3>MODIFICATIONS TO SERVICE</h3>
                <p>Perfection Consulting India reserves the right to modify or discontinue, temporarily or permanently, the service with or without notice to the user. The user agrees that Perfection Consulting India shall not be liable to the user or any third party for any modification or discontinuance of the service. The user acknowledges and agrees that any termination of service under any provision of this agreement may be effected without prior notice, and acknowledges and agrees that Perfection Consulting India may immediately delete data and files in the user's account and bar any further access to such files or the Service.</p>
                
                <h2> DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY</h2>
                <p>A great danger for Perfection Consulting India, and for all operators of online systems, is that we might be held accountable for the wrongful actions of our users. If one user libels another user, the injured user might blame us, even though the first user was really at fault. If a user uploads a program with a computer virus, and the other users' computers are damaged, we might be blamed even though a user left the virus on our System. If a user transmits illegal or improper information to another user, we might be blamed even though we did nothing more than unknowingly carry the message from one user to another. Accordingly, we need all users to accept responsibility for their own acts, and to accept that an act by another user that damages them must not be blamed on us, but only on the other user. Although it is the goal of Perfection Consulting India to provide users with reliable and quality systems, we may make mistakes or experience system failure from time to time. Such problems are inevitable in operating a system of this size. We would not be able to make this system available to users if we had to accept blame or financial liability for any usability problems, system failures or errors, or mistakes or damages of any kind. In order to continue offering and improving our service, Perfection Consulting India must deny any warranties on this service and state that our liability for any problems connected with the use of our system is strictly limited. These needs are accomplished by the following disclaimers:</p>
                
                <h3>(a) Disclaimer of Warranties</h3>
                <p>The user expressly agrees that use of the service is at the user's sole risk. The service is provided on an "as is" and "as available" basis. Perfection Consulting India expressly disclaims all warranties of any kind, whether express or implied, including, but not limited to the implied warranties of merchantability, fitness for a particular purpose and non-infringement. Perfection Consulting India makes no warranty that the service will meet a user's requirements, that the service will be uninterrupted, timely, secure, or error-free; nor does Perfection Consulting India make any warranty as to the results that may be obtained from the use of the service or as to the accuracy or reliability of any information obtained through the service or that defects in the software will be corrected. Perfection Consulting India makes no warranty regarding any goods or services purchased or information obtained through the service or any transactions entered into through the service. No advice or information, whether oral or written, obtained by the User from Perfection Consulting India shall create any warranty not expressly stated herein. </p>
                
                <h3>(b) Limitation of Liability</h3>
                <p>The user agrees that Perfection Consulting India shall not be liable for any direct, indirect, incidental, special or consequential damages resulting from the use or the inability to use the service or for the cost of procurement of substitute goods and services or resulting from any goods or services purchased or obtained or messages received or transactions entered into through or from the service or resulting from unauthorized access to or alteration of user's transmissions or data, including, but not limited to damages for loss of profits, use, data or other intangibles, even if Perfection Consulting India has been advised of the possibility of such damages. The user further agrees that Perfection Consulting India shall not be liable for any damages arising from interruption, suspension or termination of service, including, but not limited to direct, indirect, incidental, special, consequential or exemplary damages, whether or not such interruption, suspension or termination was justified, negligent, intentional or inadvertent.</p>
                
                <h3>ARBITRATION</h3>
                <p>Any controversy or claim arising out of or relating to this Agreement or Perfection Consulting India services shall be settled by binding Arbitration in accordance with laws of India. Any such controversy or claim shall be arbitrated on an individual basis, and shall not be consolidated in any arbitration with any claim or controversy of any other party. Any other dispute or disagreement of a legal nature will also be decided in accordance with the laws of India, and the Courts of Chirawa shall have jurisdiction in all such cases.</p>
                
                <h3>DISCLAIMER POLICY</h3>
                <p>Please read this document carefully before accessing or using the site. By accessing or using the site, you agree to be bound by the terms and conditions set forth below. If you do not wish to be bound by these terms and conditions, you may not access or use the site. Perfection Consulting India may modify this agreement at any time, and such modifications shall be effective immediately upon posting of the modified agreement on the site. You agree to review the agreement periodically to be aware of such modifications and your continued access or use of the site shall be deemed your conclusive acceptance of the modified agreement</p>
                 
                <p>Perfection Consulting India is not responsible for any content, code or any other inaccuracies.
Perfection Consulting India makes no guarantees. In no event shall Perfection Consulting India be liable for any special, direct, indirect, consequential or incidental damages or any damages, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the content of the Service.
Perfection Consulting India reserves the right to make additions, deletions or modifications to the content of the Service at any time without prior notice.</p>
                 
                <p>The Perfection Consulting India Service and its content are provided "as is" and "as available" without any warranty or representation of any kind, either express or implied.</p>
                <p>Perfection Consulting India  is a distributor and not a publisher of content provided by third parties; As such, Perfection Consulting India exercises no editorial control over such content and makes no warranties or representations as to the accuracy, reliability or currency of any information, content, services or merchandise provided or accessible through the Perfection Consulting India Service. Without limiting the foregoing, Perfection Consulting India specifically disclaims all warranties and representations in any content transmitted in connection with the Perfection Consulting India Service or on sites that may appear as links on the Perfection Consulting India Service, or in products provided as part of or in connection with the Perfection Consulting India Service, including, without limitation, any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information provided by Perfection Consulting India or any of its affiliates, employees, officers, directors, agents or the like will create a warranty.</p>
                <p>Pricing and availability information is subject to change without notice.</p>
                <p>Without limiting the foregoing, Perfection Consulting India does not warrant that the Perfection Consulting India Service will be uninterrupted, uncorrupted, timely or error-free. No oral advice or written information provided by Perfection Consulting India or any of its affiliates, employees, officers, directors, agents or the like will create a warranty.
</p>
                <p>Pricing and availability information is subject to change without notice. Without limiting the foregoing, Perfection Consulting India does not warrant that the Perfection Consulting India Service will be uninterrupted, uncorrupted, timely or error-free.</p>
                <p>Perfection Consulting India is a platform which help you to hire Specialists only as per Information form and details you provide   Perfection Consulting India is a Private Company.  
Please note that neither Perfection Consulting India, nor any of its subsidies or employees are Specialists. We are not a firm which provides services related to Government documents and services, we also do not provide any advice and consultation for same</p>
                <p>All our Specialists are third-party individuals. Any fake or irrelevant comments made by these Specialists are not the responsibility of our company.(If there is any fake commitment or misinformation provided by any of our Specialists, please contact us. If it is found to be true, we will ban them from our portal)</p>
                <p>The Information form on our website is not a registration form; it is just a means to connect the user with the right Specialists on the basis of application details</p>
                <p>Our Business Model is to Connect User or Businesses to Right and Reliable Specialists  
The information on this website is for the purpose of knowledge only and should not be relied upon as legal advice or opinion. 
</p>
                <h3>1. Special Disclaimer</h3>
                <p>This website is Owned & Operated by a Private firm "Legal Fox India" and is not associated with the Government Department. Please note that we are a facilitating platform enabling access to reliable Specialists. We are not a Consultancy firm and do not provide any Legal services ourselves. This is not a Government Website. The information on this website is for the purpose of knowledge only and should not be relied upon as legal advice or opinion. This Website does not provide services related to Government Documents and Services.Perfection Consulting India is an internet portal that facilitates Users to connect with G.E.M Specialists as per Information Form and facilitates communication platform. The Information form is not the actual registration form, it is just to collect information from our clients so that we can connect them with right Specialists</p>
                
                <h3>2. Form-:</h3>
                <p>The Information form on our website is not a official registration form; Its a Tool to understand your requirement with the information you provide for us and specialist</p>
                
                <h3>3.Platform Only -:</h3>
                <p>This website do not promote of any government document and services, Perfection Consulting India is an internet portal that facilitates Users to hire/connect with G.E.M Specialists as per Information Form and facilitates communication platform</p>
                
                <h3>4.Fake Commitments by Specialists All our Specialists are third-party individuals.</h3>
                <p>Any fake or irrelevant comments made by these Specialists are not the responsibility of our company. (If there is any fake commitment or misinformation provided by any of our Specialists, please contact us. If it is found to be true, we will ban them from our portal). </p>
                
                <h3>5. Fees Disclaimer</h3>
                <p>You are here by aware that Government fees for registration for G.E.M is 0/-. The fees in website includes platform fees for hiring experts.</p>
                
                <h3>OWNERSHIP</h3>
                <p>This Site is owned and operated by Perfection Consulting India. All right, title and interest in and to the materials provided on this Site, including but not limited to information, documents, logos, graphics, sounds and images (the "Materials") are owned by Perfection Consulting India. Except as otherwise expressly provided by Perfection Consulting India, none of the materials may be copied, reproduced, republished, downloaded, uploaded, posted, displayed, transmitted or distributed in any way and nothing on this Site shall be construed to confer any license under any of Perfection Consulting India's intellectual property rights, whether by estoppel, implication or otherwise. Contact us if you have any questions about obtaining such licenses. Perfection Consulting India does not sell, license, lease or otherwise provide any of the materials other than those specifically identified as being provided by Perfection Consulting India. Any rights not expressly granted herein are reserved by Perfection Consulting India.</p>
                
                <h3>ENTIRE AGREEMENT</h3>
                <p>This agreement constitutes the entire and whole agreement between user and Perfection Consulting India,and is intended as a complete and exclusive statement of the terms of the agreement. This agreement shall supersede all other communications between Perfection Consulting India and its users with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter. If at any time you find these Terms and Conditions unacceptable or if you do not agree to these Terms and Conditions, please do not use this Site. We may revise these Terms and Conditions at any time without notice to you. It is your responsibility to review these Terms and Conditions periodically. By using Perfection Consulting India services or accessing the Perfection Consulting India site, you acknowledge that you have read these terms and conditions and agree to be bound by them.</p>
                
                <h3>INDEMNIFICATION</h3>
                <p>You agree to defend, indemnify and hold harmless Perfection Consulting India, our officers, directors, shareholders, employees and agents from and against any and all claims, liabilities, damages, losses or expenses, including reasonable attorneys' fees and costs, arising out of or in any way connected with your access to or use of the site and the materials.</p>
                
                <h3>CANCELLATION AND REFUND POLICY</h3>
                <p>We thank you and appreciate You choose our platform to hire Specialists for G.E.M Registration or product purchase with us on our Website Perfection Consulting India (hereinafter referred to as “Perfection Consulting India”). Please read this policy and the Perfection Consulting India terms and conditions carefully as they will give you important information and guidelines about your rights and obligations as our customer, with respect to any purchase or Hire Specialist for G.E.M Registration services .</p>
                 
                <p>We make every effort to hire experts for you in time and also that Experts provide the service to you as per the specifications and timelines, however if, due to any reason, Experts are unable to provide you with assistance services other than consultancy services, such as Assistance in drafting and applications, which you can request from them, then you shall be entitled to a full refund which shall be subject on the following situations:</p>
                
                
                <p>1. The Refund shall be only considered in the event there is a clear, visible deficiency with the service from Specialist.</p>
                <p>2.If a customer has made a payment for a service and subsequently requests a refund solely due to a change of mind, an inadvertent application, or for any other non valid reasons without any fault, defect, or responsibility on the part of the Perfection Consulting India  and Specialists, the refund request will not be entertained.</p>
                <p>3.Refund requests shall not be entertained after the work(Application Form, Submission on govt portal and Successful Registration) has been shared by experts with you in the event of change of mind or an inadvertent application, or for any other reasons without any fault , defect, or responsibility on the part of the Experts; and</p>
                <p>4.If the request for a refund has been raised 30 (thirty) days after the purchase of a service or product has been completed and the same has been intimated and indicated via email or through any form of communication stating that the work has been completed by experts, then, such refund request shall be deemed invalid and shall not be considered.</p>
                <p>5.If the request for the refund has been approved by Perfection Consulting India, the same shall be processed and intimated to you via email. This refund process could take a minimum of 15 (fifteen) business days to process and shall be credited to your bank account accordingly. We shall handle the refund process with care and ensure that the money spent by you is returned to you at the earliest.</p>
                <p>6.In scenarios involving clerical errors attributed to experts, spanning but not limited to spelling inaccuracies, address disparities, and other common inaccuracies inherent in human activities, it is expressly acknowledged that corrective measures shall be undertaken by the experts without incurring additional costs. Nevertheless, it is underscored that no refund shall be issued under such circumstances.</p>
                <p>7.In instances where the delivery of services is impeded due to Users-related shortcomings, such as inadequate document submission, failure to provide essential information like user credentials for renewals, additional document requirements, or any other factors that hinder experts ability to provide services, refunds will not be issued.</p>
                <p>8.In Special Condition we refund 20% of paid amount, but decision is totally depend on Perfection Consulting India</p>
                <p>9.We will not be considered in breach of Satisfaction Guarantee policy or in default under any service terms, and we will not be liable to the client for any disruption, interruption, or delay in the execution of our commitments due to circumstances beyond our reasonable control, such as earthquakes, floods, fires, storms, lightning, droughts, avalanches, hurricanes, tornadoes, earthquakes, acts of God, public enemy, epidemics, famines, court or government actions, changes in law, explosions, wars, terrorism, armed conflict, labour strikes, lockouts, boycotts, or similar events, whether anticipated or unforeseen (each referred to as a "Force Majeure Event").</p>
                <p>10. Perfection Consulting India strives to make every effort to engage or establish communication with specialists within 24-48 hours. However, there may be instances when the process takes longer, potentially exceeding 15 days, depending on the availability of experts. In the event that the process of services has not commenced or communication has not been provided within 15 days of payment, a full refund is available. These services are provided based on user demand.</p>
                <p>11.If a specialist has shared an application draft before 15 days, refund will not be considered</p>
                <p>12.In scenarios involving clerical errors attributed to experts, spanning but not limited to spelling inaccuracies, address disparities, and other common inaccuracies inherent in human activities, it is expressly acknowledged that corrective measures shall be undertaken by the experts without incurring additional costs. Nevertheless, it is underscored that no refund shall be issued under such circumstances.</p>
                <p>13.Refund is not applicable for incomplete registration caused by official website malfunction or non-functionality.</p>
                <p>Contact Us Please feel free to contact us if you have any questions.Via email: care@gemregistration.co.in  Through phone number: +91-8595323374 Through this address: Perfection Consulting India Services, Plot No 24 Second Floor , Sewak Park Near Metro pillar - 771 New Delhi - 110059 </p> 
                
            </div>
        </div>
    </div>
</section> 

<?php include('footer.php'); ?> 